### ISSUE TITLE
Percentage value is not given to one of emotion in pie-chart and hover over graph that point out incorrect percentage location on graph

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#39]
**Description:**
Result of "live-stream", percentage value is missing on one of emotion in pie-chart and hover over graph that point out incorrect percentage location on graph
**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
start live-stream

**Expected result:**
percentage value should be given to predicted emotion and on graph value should be accurately point out

**Actual result:**
percentage value did not given to predicted emotion and on graph value should be accurately point out

**Picture**
![Screenshot from 2024-04-16 16-52-05](https://github.com/xiarahman/eda-ai/assets/109179391/34ce84fc-e97b-465f-889a-627be80b97b0)

**Comment by xrasad** [comment]
@shandev18 please verify the issue thanks

**Comment by shandev18** [comment]
issue fixed in the latest code

**Comment by xrasad** [comment]
@shandev18 please verify the issue it occurred again.

![Screenshot from 2024-05-06 10-51-52](https://github.com/xiarahman/eda-ai/assets/109179391/0360e0d6-0ac4-4569-972b-7dd4f7c8b952)

**Comment by shandev18** [comment]
fixed in the latest code

**Comment by xrasad** [comment]
Issue still exits 
upload video module:
![Screenshot from 2024-05-13 15-01-32](https://github.com/xiarahman/eda-ai/assets/109179391/dbc2743d-0763-40f6-a4bb-004a43874044)
live stream module:
![Screenshot from 2024-05-13 14-41-31](https://github.com/xiarahman/eda-ai/assets/109179391/8fba5d45-1dd4-4104-8ea5-9bfb4ebd41b1)

**Comment by shandev18** [comment]
@xrasad we discuss this issue i think you should close this ticket as well

**Comment by xrasad** [comment]
i had disscussed with mubashir bhai as per him, please try different approaches to resolve this issue

**Comment by shandev18** [comment]
I discussed this issue with Sir Zia and Arsalan. There are no alternative solutions at this time. We can either display it as is or hide all key labels and only show them on hover.

**Comment by shandev18** [comment]
issue fixed now the pie chart looks like this:
![image](https://github.com/xiarahman/eda-ai/assets/133768718/0320aeac-c237-44e5-8c07-a3da610261a5)

**Comment by xrasad** [comment]
issue resolved thanks
