### ISSUE TITLE
on home page invalid space divided between features carts, stars and when zoom in carts overlap on each other 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#61]
Severity: 3
Priority: 1
pictures:
![Screenshot from 2024-05-03 11-35-50](https://github.com/xiarahman/eda-ai/assets/109179391/b79ceaf7-fe84-40ce-8cd6-36ec5d3692ab)
![Screenshot from 2024-05-03 11-21-45](https://github.com/xiarahman/eda-ai/assets/109179391/590f7240-1add-4478-8052-df59afdb04a4)

**Comment by xrasad** [comment]
@shandev18 @Tehreem-personal please verify the issue

**Comment by xrasad** [comment]
@shandev18 please look into this issue and compare it figma

**Comment by shandev18** [comment]
working on it

**Comment by shandev18** [comment]
fixed

**Comment by xrasad** [comment]
Issue still exist, space between stars and cart on left side is more and less space on right side and also carts are not properly square it is horizontally larger then vertically.

![Screenshot from 2024-05-13 14-32-55](https://github.com/xiarahman/eda-ai/assets/109179391/b5103f78-0740-4ef2-8b58-19abe6708b78)

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
thanks issue is fixed
