### ISSUE TITLE
URL display when you hover invalid video 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#71]
Description:
when you upload invalid video format and when you hover over the file it display URL in the message, which make no sense for user 
severity: s3

Priority: p2

Execution steps:
Go to http://localhost:3000/analyze
Drag or upload video

Expected result:
The system either display proper message that make sense for user when mouse cursor hover

Actual result:
The system display URL 

Picture:
![Screenshot from 2024-05-14 11-33-40](https://github.com/xiarahman/eda-ai/assets/109179391/72eb493a-7fd2-4d8f-b669-fedab91d1e2b)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
We now display the supported formats on the uploader and have fixed all format issues. This ensures that only supported files are shown to the user in the dialog box, reducing the likelihood of error messages. As a result, there is no need to update the UI to show error messages, as discussed with the UI and frontend teams.

**Comment by xrasad** [comment]
As per mubashir bhai, it should be handle from UI

**Comment by shandev18** [comment]
fixed now URL did not show on hover

**Comment by xrasad** [comment]
@shandev18 i had pulled latest changes from eda_4 branch but the issue still exist

**Comment by shandev18** [comment]
fixed

**Comment by xrasad** [comment]
issue fixed
